//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class BULK_UPLOAD
    {
        public int IMG_ID { get; set; }
        public byte[] IMG { get; set; }
    }
}
